### ISSUE TITLE
FEATURE REQUEST: save item catalogue as a table

### ISSUE THREAD

**Issue by chibbi** [raninninn/CC-plethora-inventory-system#1]
#### First Proposal:
Save the whole item catalogue as a table inside of a file and process the table to be seen in the way it is currently seen.

#### Second Proposal:
Also safe where the item is stored (which chest, and ideally the slot too)

## Advantages:
Allows easier processing for new methods like "find" because you can process the table directly instead of having to process the catalogue into a processable form first.

## Disadvantages:
You have to process the item catalogue when you want to see the whole catalogue.

**Comment by raninninn** [comment]
Item catalogue is now saved as clear text and as a table
