### ISSUE TITLE
Also load the table into the program

### ISSUE THREAD

**Issue by chibbi** [raninninn/CC-plethora-inventory-system#11]
**Is your feature request related to a problem? Please describe.**
i have to rebuild the program everytime i wanna use the table after stopping the program

**Describe the solution you'd like**
Load the table out of the file into the program.

**Describe alternatives you've considered**
there is no other way

**Additional context**
You know you already shouldve done it.

**Comment by raninninn** [comment]
Done. Also shouldn't you have already done a fork that implements a fork function? ;)
