### ISSUE TITLE
DOCUMENTATION: explain that plethora is an addon for cc-tweaked

### ISSUE THREAD

**Issue by chibbi** [raninninn/CC-plethora-inventory-system#2]
## Proposal:
Write into your README that you use cc-tweaked with the addon plethora, so people who don't know plethora/cc-tweaked know that too.

## Advantages:
More friendly for people who don't know the mods.

## Disadvantages:
You have to write a line into your Readme xD

**Comment by raninninn** [comment]
Added your proposal.
