### ISSUE TITLE
a better "unkown command" message

### ISSUE THREAD

**Issue by chibbi** [raninninn/CC-plethora-inventory-system#8]
**Is your feature request related to a problem? Please describe.**
Have a better  "unkown command" message

**Describe the solution you'd like**
something more standard like:
```
invalid command
Try 'help' for more information.
```

**Describe alternatives you've considered**
Leave it as it is or only add ```try "help"```

**Additional context**
```
cat: invalid option -- 'g'
Try 'cat --help' for more information.
```

**Comment by raninninn** [comment]
Fixed in #9
